blog/apps/posts/urls.py
from django.urls import path

# importar views
from . import views

app_name= "posts"

urlpatterns = [
    path("", views.inicio_post, name="Inicio"),
    path("categorias/", views.categorias_post, name="categorias"),
    path("posts/", views.posts, name="posts"),
    path("post_detail/<int:post_id>", views.post_detail, name="post_detail"),
    path("comentario", views.comentar_posteo, name="comentar"),
    path("borrar/<int:pk>", views.Borrar_Comentario.as_view(), name="borrar_comentario"),
    path("modificar/<int:pk>", views.Modificar_Comentario.as_view(), name="modificar_comentario"),
]

blog/apps/usuarios/urls.py
from django.urls import path

# importar views
from . import views

app_name= "usuarios"

urlpatterns = [path("registro/", views.registro, name="registro")]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('apps.posts.urls')),
    path("login/", LoginView.as_view(template_name = "usuarios/login.html"), name= "login"),
    path("logout/", LogoutView.as_view(template_name = "usuarios/logouthtml"), name= "logout"),
    path("usuarios/", include('apps.usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/posts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.



class Categoria(models.Model):
    nombre = models.CharField(max_length=50, null=False)
    
    def __str__(self) -> str:
        return self.nombre

class Post(models.Model):
    titulo = models.CharField(max_length=50, null=False)
    subtitulo = models.CharField(max_length=100, null=True, blank=True)
    fecha = models.DateTimeField(auto_now_add=True)
    texto = RichTextField(null=False)
    activo = models.BooleanField(default=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, null=True, default="Sin categoría")
    imagen = models.ImageField(null=True, blank=True, upload_to="posts/img", default="static/img/post_default.png")
    publicado = models.DateTimeField(default=timezone.now)
    
    class Meta:
        ordering = ("-publicado",)

    def comentarios_realizados(self):
        return self.comentario_set.all()


    def __str__(self):
        return self.titulo
    
    def delete(self, using = None, keep_parents = False):
        self.imagen.delete(self.imagen.name)
        super().delete()

class Comentario(models.Model):
    texto = models.TextField(null= False)
    fecha = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return f"{self.post} {self.texto}"

blog/apps/usuarios/models.py
from django.db import models

# Create your models here.

blog/apps/posts/forms.py
from django import forms
from .models import Comentario

class Formulario_Modificacion(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ("texto",)

blog/apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class FormularioRegistro(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirmar Contraseña", widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

blog/apps/posts/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import *
from django.views.generic import DeleteView, UpdateView
from django.urls import reverse_lazy
from .forms import Formulario_Modificacion

# Create your views here.

def inicio_post(request):
    ctx = {}
    posteos = Post.objects.filter().order_by('-id')[:3]
    ctx['trending']=posteos
    return render(request, "inicio.html", ctx)

def categorias_post(request):
    categorias = Categoria.objects.all()
    ctx = {'categorias':categorias}
    return render(request, "posts/categorias.html", ctx)

def posts(request):

    id_categoria = request.GET.get('id', None)
    antiguedad = request.GET.get("orden", None)
    alfabetico = request.GET.get("orden", None)
    ctx = {}

    if id_categoria:
        posteos = Post.objects.filter(categoria=id_categoria)
    else:
        if antiguedad == "asc":
            posteos = Post.objects.all().order_by("fecha")
        elif alfabetico == "a":
            posteos = Post.objects.all().order_by("titulo")
        elif alfabetico == "z":
            posteos = Post.objects.all().order_by("-titulo")
        else:
            posteos = Post.objects.all().order_by("-fecha")

    
    categorias = Categoria.objects.all()
    ctx["posteos"]= posteos
    ctx["categorias"]= categorias
    

    return render(request, "posts/post.html", {"categorias": categorias, "posteos": posteos})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    ctx = {"post": post}
    return render(request, "posts/post_detail.html", ctx)

def comentar_posteo(request):
    comentario = request.POST.get("comentario", None)
    usuario = request.user
    post = request.POST.get("id_post", None)
    posteo = Post.objects.get(id=post)
    setear_comentario = Comentario.objects.create(
        usuario = usuario,
        post = posteo,
        texto = comentario,
    )
    return redirect("posts:post_detail", post_id=post)

class Borrar_Comentario(DeleteView):
    model = Comentario
    template_name = "comentarios/confirm_delete.html"
    success_url = reverse_lazy("posts:posts")

class Modificar_Comentario(UpdateView):
    model = Comentario
    form_class = Formulario_Modificacion
    template_name = "comentarios/modificar.html"
    context_object_name = "com"
    success_url = reverse_lazy("posts:posts")

blog/apps/usuarios/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
# Create your views here.
from .forms import FormularioRegistro
from django.contrib import messages


def registro(request):
    contexto={}

    if request.method == "POST":
        formulario = FormularioRegistro(request.POST)
        if formulario.is_valid():
            formulario.save()
            nombre_usuario = formulario.cleaned_data["username"]
            messages.success(request, f"Usuario {nombre_usuario} creado.")
            return redirect(reverse("posts:Inicio"))
    else:
        formulario = FormularioRegistro()

    contexto["form"] = formulario
    return render(request, "usuarios/register.html", contexto)

blog/blog/views.py
# render
from django.shortcuts import render

# Portada de pagina

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-ar">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="icon" href="{% static 'img/icono.ico' %}">
  <title>
    {% block title %}
    Titulo de la pagina
    {% endblock title %}
  </title>
</head>

<body>
  {% if messages %}
  {% for message in messages %}
  <div>{{ message }}</div>
  {% endfor %}
  {% endif %}
  <header class="p-3 text-white bg-black">

    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'posts:Inicio' %}" class="nav-link px-2 text-white">Cine De Culto</a></li>
        <li><a href="#Nosotros" class="nav-link px-2 text-white">Sobre Nosotros</a></li>
        <li><a href="#Contactos" class="nav-link px-2 text-white">Contacto</a></li>
        {% if user.is_authenticated and user.is_staff%}
        <li><a href="{% url 'admin:index' %}" class="nav-link px-2 text-white">Administrar</a></li>
        {% endif %}
        {% block filtro %}

        {% endblock filtro %}
      </ul>
      <div class="text-end">
        {% if user.is_authenticated %}
        Bienvenido {{ user.username }}!
        <a type=button class="btn btn-outline-light" href="{% url 'logout' %}">Cerrar Sesión</a></button>
        {% else %}
        <a type=button class="btn btn-outline-light" href="{% url 'login' %}">Iniciar Sesión</a></button>
        <a type="button" class="btn btn-outline-light" href="{% url 'usuarios:registro' %}">Registrarse</a></button>
        {% endif %}
      </div>
    </div>

  </header>

  <div class="container">
    {% block contenido %}
    Contenido de la pagina
    {% endblock contenido %}
  </div>
  <br>

  <footer class="py-2 bg-black footer">
    <div class="container text-center text-white">
      <section id="Nosotros">
      <h3>Sobre Nosotros</h3>
        <ul class="container">
          <p>
            Esta pagina web fue desarrollada por
            Iván Nuñez Londero,
            Juan Ramón Bertoli Rojas
            y Jonathan Ezequiel Quain
            para el Informatorio
          </p>
        </ul>  
      </section>    
      <hr>
      <section id="Contactos">
      <h3>Contactos</h3>
      <ul class="container">
        <a href="https://mail.google.com/mail/?view=cm&amp;fs=1&amp;tf=1&amp;to=ivanlondero17@gmail.com&amp;body=">Iván Nuñez Londero</a>
        <hr>
        <a href="https://mail.google.com/mail/?view=cm&amp;fs=1&amp;tf=1&amp;to=bertolijuan777@gmail.com&amp;body=">Juan Ramón Bertoli Rojas</a>
        <hr>
        <a href="https://mail.google.com/mail/?view=cm&amp;fs=1&amp;tf=1&amp;to=ezequielquain@gmail.com&amp;body=">Jonathan Ezequiel Quain</a>
      </ul>
      </section>
    </div>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
</body>

</html>

blog/templates/comentarios/confirm_delete.html
{% extends 'usuarios/register.html' %}

{% block title %}
    Eliminar comentario
{% endblock title %}

{% block contenido %}
<div class="text-white">
    <form method="POST" class="confirm-box">
        {% csrf_token %}
        <h1>¿Deseas borrar este comentario?</h1>
        {{ form }}
        <button type="submit" class="btn btn-danger centrar"> Confirmar </button>
    </form>
</div>
{% endblock contenido %}

blog/templates/comentarios/modificar.html
{% extends 'usuarios/register.html' %}

{% block title %}
    Modificar Comentario
{% endblock title %}

{% block contenido %}
<form method="POST">
    {% csrf_token %}
    <div  class="form-group mb-3 caja-centro">
        <label for="comentario" class="form-label boton-modificar">Modificar comentario</label>
        <textarea class="form-control" id="comentario" name="texto" rows="5" placeholder="Modifica tu comentario aquí" required>{{ com.texto }}</textarea>        
        <button type="submit" class="btn btn-success boton-modificar">Confirmar</button>
    </div>
</form>


<!-- <div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card bg-light">
                <div class="card-header bg-primary text-white">
                    <h2 class="mb-0">Modificar Comentario</h2>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.as_p }}
                        </div>
                        <button type="submit" class="btn btn-success">Confirmar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div> -->
{% endblock contenido %}

blog/templates/inicio.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Cine de culto
{% endblock title %}

{% block contenido %}
<div class="text-white">
  <h2>¡No podes no verlas!</h2>
  <p>
    Si sos una persona que no consume cine y no tenés idea sobre qué ver, ¡esta página es la indicada!<br> Te traemos un catálogo de grandes películas de esta época para que te pongas al día y puedas comenzar a hablar con tus amigos sobre el <b>cine de culto.</b> <br>
  </p>

<hr>
<h1> Tendencias</h1>
</div>
<br>
<div class="container text-center">
  <div class="row">
    {% for post in trending %}
    <div class="col">
      <div class="card text-bg-dark mb-3" style="max-width: 540px;">
        <div class="card-img-container">
          <img src="{{ post.imagen.url }}" class="card-img" alt="No Hay Imagen">
          <div class="card-body description-hidden">
            <h5 class="card-title">{{ post.titulo }}</h5>
            <p class="card-text">{{ post.subtitulo }}</p>
          </div>
        </div>
        <div class="card-footer text-center" style="background-color: black; color: white;">
          <ul class="list-group list-group-flush" style="background-color: black; color: white;">
            <li class="list-group-item" style="background-color: black; color: white;">Publicado: {{ post.fecha }}</li>
            <li class="list-group-item" style="background-color: black; color: white;">{{ post.categoria }}</li>
          </ul>
          <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-primary mt-2">Ver Post</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<style>
  .card-img-container {
    position: relative;
  }

  .card-body {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    opacity: 0;
    transition: opacity 0.3s ease-in-out;
  }

  .card-img-container:hover .card-body {
    opacity: 1;
  }
</style>
<div class="contenedor-post">
<a href="{% url 'posts:posts' %}" class= "text-white" >Ver más posts</a>
</div>
{% endblock contenido %}

blog/templates/posts/post.html
{% extends "base.html" %}
    
{% block title %}
    Posteos
{% endblock title %}

{% block filtro %}
<li><a href="{% url 'posts:Inicio' %}" class="nav-link px-2 text-white">Regresar</a></li>
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Filtro
  </a>
  <ul class="dropdown-menu"> 
    <li>Categoria</li>
    {% for categoria in categorias %}
    <li><a class="dropdown-item" href="?id={{categoria.pk}}">{{categoria.nombre}}</a></li>
    {% endfor %}            
    <li><hr class="dropdown-divider">Fecha</li>
    <li><a class="dropdown-item" href="?orden=desc">Más recientes</a></li>   
    <li><a class="dropdown-item" href="?orden=asc">Más antiguos</a></li>     
    <li><hr class="dropdown-divider">Letra</li>
    <li><a class="dropdown-item" href="?orden=a">A-Z</a></li>    
    <li><a class="dropdown-item" href="?orden=z">Z-A</a></li>    
  </ul>
</li>
{% endblock filtro %}

{% block contenido %}


<br>
<div class="container text-center">
  <div class="row">
    {% for post in posteos %}
      <div class="col-3">
        <div class="card text-bg-dark mb-3" style="max-width: 540px;">
          <div class="card-img-container">
            <img src="{{ post.imagen.url }}" class="card-img" alt="No Hay Imagen">
            <div class="card-body description-hidden">
              <h2 class="card-title">{{ post.titulo }}</h2>
              <p class="card-text">{{ post.subtitulo }}</p>
            </div>
          </div>
          <div class="card-footer text-center" style="background-color: black; color: white;">
            <ul class="list-group list-group-flush" style="background-color: black; color: white;">
              <li class="list-group-item" style="background-color: black; color: white;">Publicado: {{ post.fecha }}</li>
              <li class="list-group-item" style="background-color: black; color: white;">{{ post.categoria }}</li>
            </ul>
            <a href="{% url 'posts:post_detail' post.id %}" class="btn btn-primary mt-2">Ver Post</a>
          </div>
        </div>
      </div>
    {% empty %}
    <h1>No Hay Posts</h1>
    {% endfor %}   
  </div>
</div>


<style>
  .card-img-container {
    position: relative;
  }

  .card-body {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    opacity: 0;
    transition: opacity 0.3s ease-in-out;
  }

  .card-img-container:hover .card-body {
    opacity: 1;
  }
</style>
{% endblock contenido %}

blog/templates/posts/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    {{ post.titulo }}
{% endblock %}

{% block filtro %}
<li><a href="{% url 'posts:posts' %}" class="nav-link px-2 text-white">Regresar</a></li>
{% endblock filtro %}

{% block contenido %}
    <style>
        body {
            background-color: #1a1a1a; /* Fondo negro */
            color: #fff;
        }

        .post-container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #2d2d2d; /* Fondo gris oscuro */
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        }

        .post-image {
            max-width: 100%;
            height: auto;
            border-radius: 8px;
            margin-bottom: 20px;
        }

        .post-text {
            max-height: 200px;
            overflow-y: auto;
            font-size: 16px;
            line-height: 1.6;
        }

        .comentarios-section {
            margin-top: 20px;
        }

        .comentario {
            background-color: #333; /* Fondo oscuro para comentarios */
            padding: 10px;
            border-radius: 8px;
            margin-bottom: 10px;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.5);
        }

        .comentario-date {
            color: #777;
        }

        .comentario-usuario {
            font-weight: bold;
        }

        .comentario-text {
            margin-top: 10px;
            font-size: 14px;
        }

        /* Botón de Comentar */
        .btn-comentar {
            background-color: #007bff; /* Azul */
            color: #fff;
            border: none;
            border-radius: 4px;
            padding: 10px 15px;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        .btn-comentar:hover {
            background-color: #0056b3; /* Azul más oscuro al pasar el ratón */
        }
    </style>

    <div class="post-container">
        <img src="{{ post.imagen.url }}" alt="No Hay Imagen" class="post-image">
        <h1>{{ post.titulo }}</h1>
        <p class="post-date">{{ post.fecha }}</p>

        <div class="description-container">
            <p class="post-text">{{ post.texto | safe }}</p>
        </div>
        <hr>
        {% if user.is_authenticated %}
        <form action="{% url 'posts:comentar' %}" method="POST" class="mt-3">
            {% csrf_token %}
            <div class="mb-3">
                <label for="comentario" class="form-label">Agregar un comentario</label>
                <textarea class="form-control" id="comentario" name="comentario" rows="5" placeholder="Escribe tu comentario aquí" required></textarea>
            </div>
            <input type="text" name="id_post" value="{{ post.id }}" hidden>
            <button type="submit" class="btn btn-comentar">Comentar</button>
        </form>

        {% else %}
        <div class="mb-3">
            <label for="comentario" class="form-label">Agregar un comentario</label>
            <textarea class="form-control" id="comentario" name="comentario" rows="5" placeholder="Registrate o inicia sesión para comentar!"></textarea>
        </div>
        <a type=button class="btn btn-outline-light" href="{% url 'login' %}" >Iniciar Sesión</a></button>
        <a type="button" class="btn btn-outline-light" href="{% url 'usuarios:registro' %}">Registrarse</a></button>
        {% endif %}
        {% for comentario in post.comentarios_realizados %}
        <div class="comentarios-section comentario mt-3">

                <p class="comentario-date">{{ comentario.fecha }}</p>
                <p class="comentario-usuario">{{ comentario.usuario }} comentó</p>
                <p class="comentario-text">{{ comentario.texto }}</p>
                {% if user.is_authenticated and user.id == comentario.usuario_id or user.id == user.is_staff %}
                <a href="{% url 'posts:modificar_comentario' comentario.pk %}" type="button" class="btn btn-success">modificar</a>                    
                <a href="{% url 'posts:borrar_comentario' comentario.pk %}" type="button" class="btn btn-danger">borrar</a>
                {% endif %}

        </div>
        {% endfor %}

        
    </div>

    <!-- Agrega el CDN de Bootstrap al final del archivo para incluirlo -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}

blog/templates/usuarios/login.html
{% extends 'usuarios/register.html' %}

{% block title %}
	Inicio de sesion
{% endblock %}


{% block contenido %}
<div class="container-login">
<div class="text-white form-login login-box">
	<h3>Inicio de sesión</h3>
	<form method="POST">
		{% csrf_token %}
		<label for="{{ form.username.id_for_label }}"> usuario </label>
		{{ form.username }}
		{{ form.username.errors }}
		<label for="{{ form.password.id_for_label }}"> contraseña </label>
		{{ form.password }}
		{{ form.password1.errors }}
		<input type="submit" class="btn btn-primary" value="Iniciar sesión">
	</form>
</div>
</div>
{% endblock %}

blog/templates/usuarios/logout.html
<h1>Sesion finalizada</h1>

blog/templates/usuarios/register.html
{% load static %}
<!DOCTYPE html>
<html lang="es-ar">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="icon" href="{% static 'img/icono.ico' %}">

  <title>
	{% block title %}
	Registro
	{% endblock title %}
  </title>

</head>

<body>
<a href="{% url 'posts:Inicio' %}" class="boton-back btn btn-primary text-white">Regresar</a>
{% block contenido %}
<div class="text-white register-box">
	<h1>Registro</h1>
	<form method="POST">
		{% csrf_token %}
		<label for="{{ form.username.id_for_label }}">Nombre de usuario:</label>
		{{ form.username }}
		{{ form.username.errors }}
		<label for="{{ form.username.id_for_label }}">Email:</label>
		{{ form.email }}
		{{ form.email.errors }}
		<label for="{{ form.username.id_for_label }}">Contraseña:</label>
		{{ form.password1 }} 
		{{ form.password1.errors }}
		<label for="{{ form.username.id_for_label }}">Confirmar Contraseña:</label>
		{{ form.password2 }} 
		{{ form.password2.errors }}
		<input type="submit" id="submit" value="Registrarse" class="btn btn-primary">
	</form>
</div>
{% endblock contenido %}
</body>
</html>